sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR/paper,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic beane_paper.tex"
  #- docker tectonic paper/beane_paper.tex
  - source .ci/build-paper.sh

#sudo: require 
#language: generic
#matrix:
#  include:
#    - os: linux
#      env: TEST_LANG='paper'
#
#script: |
#  if [[ $TEST_LANG == paper ]]
#  then
#    source .ci/build-paper.sh
#  fi
