sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - source .ci/build-paper.sh

#sudo: require 
#language: generic
#matrix:
#  include:
#    - os: linux
#      env: TEST_LANG='paper'
#
#script: |
#  if [[ $TEST_LANG == paper ]]
#  then
#    source .ci/build-paper.sh
#  fi
